spring.application.name=TaskProject
## default connection pool
spring.datasource.hikari.connectionTimeout=2000
spring.datasource.hikari.maximumPoolSize=5
loggin.pattern.console=%-5level %logger{36} = %msg%n
## PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:15432/PostgreSQLWebApp
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver
#drop n create table again, good for testing, comment this in production
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
management.endpoints.web.exposure.include=*
